SELECT * FROM profesionales;

insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (1, 'Hansiain', 'Stolz', '1982-01-08', '345 Corscot Road', '(205) 8597782', 'hstolz0@auda.org.au', 1, 1);
insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (2, 'Marta', 'Speek', '1979-11-09', '69970 Eastlawn Road', '(659) 3008259', 'mspeek1@europa.eu', 1, 7);
insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (3, 'Fleming', 'Sellors', '1971-09-18', '27804 Erie Alley', '(561) 6872517', 'fsellors2@slate.com', 1, 11);
insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (4, 'Tull', 'Semechik', '1989-10-21', '8994 Norway Maple Junction', '(627) 4510561', 'tsemechik3@elegantthemes.com', 1, 4);
insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (5, 'Bella', 'Rijkeseis', '1987-04-03', '93 Pepper Wood Pass', '(944) 2500024', 'brijkeseis4@mozilla.org', 3, 8);
insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (6, 'Harwilll', 'Skeene', '1989-02-08', '1842 Del Mar Park', '(760) 4548906', 'hskeene5@imdb.com', 3, 2);
insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (7, 'Justis', 'Wallworth', '1996-03-14', '4 Hanover Center', '(719) 9903209', 'jwallworth6@xinhuanet.com', 3, 7);
insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (8, 'Justus', 'Sherebrooke', '1990-07-25', '536 Browning Place', '(996) 7867412', 'jsherebrooke7@nationalgeographic.com', 2, 2);
insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (9, 'Papageno', 'Covet', '1957-01-01', '9148 Heffernan Avenue', '(199) 4649304', 'pcovet8@ftc.gov', 2, 2);
insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (10, 'Anatol', 'Hundall', '1998-11-13', '56 Kensington Hill', '(222) 8186346', 'ahundall9@narod.ru', 2, 11);
insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (11, 'Onida', 'Wolters', '1995-01-13', '2 Northport Crossing', '(555) 8884761', 'owoltersa@cloudflare.com', 3, 4);
insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (12, 'Amy', 'Deetlefs', '1950-12-17', '620 Golf Alley', '(235) 5624895', 'adeetlefsb@patch.com', 3, 4);
insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (13, 'Jena', 'Kless', '1966-12-17', '54 Fuller Way', '(465) 9809314', 'jklessc@lycos.com', 1, 8);
insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (14, 'Karoly', 'Rumbold', '1985-09-03', '041 Monica Plaza', '(806) 7637365', 'krumboldd@slate.com', 3, 8);
insert into profesionales (Legajo, Nombre_PF, Apellido_PF, Fecha_Nac, Domicilio_PF, Tel_Contacto, Email_PF, Localidad_PF, Especialidad) values (15, 'Gifford', 'Bysh', '1958-06-29', '6 Donald Road', '(461) 2206117', 'gbyshe@mlb.com', 1, 6);